### ISSUE TITLE
Resove the current CI issues 

### ISSUE THREAD

**Issue by Shelley-BaoYue** [kubeedge/ianvs#109]
**What happened**:

CI is always failed even if we push an unrelated code. 

**What you expected to happen**:

CI runs successfully

**How to reproduce it (as minimally and precisely as possible)**:

Look at the CI results of any PR. 

**Anything else we need to know?**:

uvicorn version 0.14.0 in Sedna needs to be upgraded as I have also submit a issue in Sedna https://github.com/kubeedge/sedna/issues/432, because pip form 24.1 no longer support uvicorn 0.14.0. 

However I tried to use PIP 24.0 to cover this problem,

![image](https://github.com/kubeedge/ianvs/assets/48788150/ef95a9b1-ecf0-46e7-8b37-7629bd6c0016)

new error in CI occured like:

https://github.com/kubeedge/ianvs/actions/runs/9612294929/job/26512623096 

![image](https://github.com/kubeedge/ianvs/assets/48788150/2d7c03b7-1018-472b-8f85-e2d8000daace)

**Comment by hsj576** [comment]
Add "# pylint: disable=R0801" in these files could solve the CI error.

**Comment by Shelley-BaoYue** [comment]
When I add "# pylint: disable=R0801", there are still many other errors like below:

![image](https://github.com/kubeedge/ianvs/assets/48788150/df6d3c37-fd3f-4c05-8227-2f472d560fe3)

I think we need to solve the pip version first, and then handle these pylint errors.
