### ISSUE TITLE
Issue with Installation:  Outdated Dependencies and Incomplete Configuration for Ianvs Installation

### ISSUE THREAD

**Issue by aryan0931** [kubeedge/ianvs#142]
Description
We are encountering significant issues with the installation of the Ianvs project due to outdated dependencies and deprecated  APIs, particularly related to the Sedna package. These issues lead to confusion and errors during installation and configuration.

 **Details:**
Deprecated APIs: Some APIs from older versions of Sedna have been deprecated, causing errors and compatibility issues.
Incomplete Dependencies: The current requirements.txt does not fully specify all necessary dependencies or their compatible  versions.

 **Steps to Reproduce**
Attempt to install Ianvs following the current instructions.
Encounter errors related to deprecated APIs from Sedna.
 Observe that the current version of Sedna may not be compatible with Ianvs.

**Expected Behavior**
Ianvs should install successfully with all dependencies resolved.
 All components should be compatible with the latest versions of their dependencies.

 **Actual Behavior**
Errors occur during installation related to deprecated APIs from Sedna.
Dependencies are unclear or incomplete, causing issues with environment configuration.

Suggested Fixes

Update Dependencies:
Ensure that Sedna and its submodules are correctly installed and accessible.
 Specify and verify the correct version of Sedna that is compatible with Ianvs.

**I suggest:**
  Completing the dependencies for Ianvs Core, and updating [requirements.txt](https://github.com/kubeedge/ianvs/blob/main/requirements.txt) 
   

<img width="1270" alt="Screenshot 2024-09-06 at 2 17 03 PM" src="https://github.com/user-attachments/assets/f346aaa2-3ce7-4ba0-87ca-15fbe0844e73">

**Comment by FuryMartin** [comment]
Hi, I encountered the same issue (see #132) and am trying to resolve it with the community.

If you want to experience Ianvs right now, you can try installing my modified sedna package:
https://github.com/FuryMartin/sedna/releases/tag/v0.4.1.1

In this version, I fixed some version issues in Sedna's requirements.txt.


Besides, Ianvs's [Quick Start example](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) has some issues; I've provided a modified repository and running instructions for your reference:
https://github.com/FuryMartin/ianvs/tree/quickstart/examples/pcb-aoi/singletask_learning_bench/fault%20detection

**Comment by aryan0931** [comment]
> Hi, I encountered the same issue (see #132) and am trying to resolve it with the community.
> 
> If you want to experience Ianvs right now, you can try installing my modified sedna package: https://github.com/FuryMartin/sedna/releases/tag/v0.4.1.1
> 
> In this version, I fixed some version issues in Sedna's requirements.txt.
> 
> Besides, Ianvs's [Quick Start example](https://ianvs.readthedocs.io/en/latest/guides/quick-start.html) has some issues; I've provided a modified repository and running instructions for your reference: https://github.com/FuryMartin/ianvs/tree/quickstart/examples/pcb-aoi/singletask_learning_bench/fault%20detection

ok, I will go through this
