### ISSUE TITLE
Link model codes url to ianvs directly instead of packaging models as third-party wheels

### ISSUE THREAD

**Issue by xiaochanwang** [kubeedge/ianvs#15]
**What would you like to be added/modified**:
I wonder if it's possible for ianvs to mount local model codes url (e.g., local directory) right into `algorithm.yaml` (or other config files) instead of packaging models as third-party wheels.

**Why is this needed**:
Packaging local model codes might be tedious or even difficult for algorithm developers. More efficient and lightweight develop methods are preferred.

**Comment by JimmyYang20** [comment]
@xiaochanwang 
provide two solutions：
1. add your third-party package's url to PYTHONPATH
2. ` import sys; sys.path.append(url)`
